### ISSUE TITLE
Resume work on the webpage

### ISSUE THREAD

**Issue by VTIvanov20** [codingburgas/cup-2022-yottabyte#6]
### Synopsis
Our website might not seem like something of high importance, but it will give the user a good first impression, once it is completed.

Various micro-interactions have planned in the design, that will surely catch the attention of our desired clients.

<hr>

### Tasks:

- [ ] Finalize the Landing screen
- [ ] Start working on and eventually finalize the Functionality screen
- [ ] Start working on and eventually finalize the Social screen
- [ ] Start working on and eventually finalize the Register screen + form
- [ ] Add parallax scrolling effects to the SVG lines, meant to connect various assets.
- [ ] Swap out the photos, used in the design.

<hr>

### Required Members:

- @BNSavov19 
- @VTIvanov20 
- @KNTaligadzhiev19
